---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyrtr.fullname" . }}-http
  labels:
    {{- include "pyrtr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "pyrtr.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyrtr.fullname" . }}-rtr
  labels:
    {{- include "pyrtr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rtr.type }}
  ports:
    - port: {{ .Values.service.rtr.port }}
      targetPort: 8323
      protocol: TCP
      name: rtr
  selector:
    {{- include "pyrtr.selectorLabels" . | nindent 4 }}
